---
title: "Code"
author: "Martin Kosík"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(sf)
library(mapview)
library(mapedit)
library(USAboundaries)
library(USAboundariesData)
library(broom)
library(s2)
library(estimatr)
library(knitr)
library(kableExtra)
library(modelsummary)
library(DoubleML)
library(data.table)
library(rvest)
library(table1)
library(gt)
library(RStata)
#options("RStata.StataPath" = "C:/Users/marti/Downloads/Stata-MP-16.0/")
options("RStata.StataPath" =  "\"C:\\Users\\marti\\Downloads\\Stata-MP-16.0\\Stata-MP-16.0\\StataMP-64\"")

options("RStata.StataVersion" = 16)
#library(LATEtest)
library(robomit)
```

```{r}
library(devtools)
install_github("farbmacher/LATEtest")

```


## Data pre-processing

```{r}
sherman_march_map <- st_read(here::here("maps/sherman_march/sherman_march_shapefile_v2.shp")) #%>% st_set_crs("+proj=longlat +datum=WGS84 +no_defs")

#plot(sherman_march_map)
counties  <- us_counties(states = c("Georgia", "North Carolina", "South Carolina")) %>% 
  mutate(fips = as.numeric(paste0(statefp, countyfp)))

counties_1860  <- us_counties(states = c("1866-09-17", "Georgia", "North Carolina", "South Carolina")) %>% 
  mutate(fips = as.numeric(paste0(statefp, countyfp)))




conf_mon <- read_csv(here::here("data/conf_monuments.csv")) %>% 
  separate(Coordinates, into = c("lon", "lat"), sep = ", ", remove = FALSE, convert = TRUE) %>% 
  mutate(lon = as.numeric(lon), 
         lat = as.numeric(lat)) %>% 
  filter(!is.na(lon)) %>% 
  st_as_sf(coords = c("lat","lon"), crs = 4326) # %>% st_set_crs("+proj=longlat +datum=WGS84 +no_defs")

#mapview(conf_mon)


mon_by_county <- counties %>% 
  st_join(conf_mon) %>% 
  st_set_geometry(NULL) %>% 
  group_by(fips) %>% 
  summarize(monuments = sum(!is.na(feature_name))) 
  
```

```{r}
march_buffer_10km <- sherman_march_map %>% 
  st_transform(crs = 7801) %>% 
  st_buffer(dist = 10000, nQuadSegs = 1) 


march_buffer_5miles <- sherman_march_map %>% 
  st_transform(crs = 7801) %>% 
  st_buffer(dist = 8046.72, nQuadSegs = 1) 

march_buffer_5km <- sherman_march_map %>% 
  st_transform(crs = 7801) %>% 
  st_buffer(dist = 8046.72, nQuadSegs = 1) 

  
 # mapview(counties) %>% 
  #editMap()
```

```{r}
march_counties <- counties %>% 
  st_transform(crs = 7801) %>% 
  #st_as_s2() %>% 
  st_intersection(march_buffer_5miles) %>% 
  st_set_geometry(NULL) %>% 
  distinct(fips) %>% #count(fips, sort = T)
  dplyr::select(fips) %>% 
  mutate(march = 1)


conf_streets <-  read_csv('data/conf_streets_by_county.csv') %>% 
  mutate(fips = as.numeric(str_c(statefp, countyfp)),
         pct_conf_streets_surname = (conf_streets_surname/n_streets) * 100, 
         pct_conf_streets_both = (conf_streets_both/n_streets) * 100) %>% 
  dplyr::select(-c(statefp, countyfp))
  


counties <- counties %>% 
  left_join(march_counties, by = "fips") %>% 
  left_join(mon_by_county, by = "fips") %>% 
  left_join(conf_streets, by = "fips") %>% 
  mutate(march = ifelse(is.na(march), 0, march), 
         monuments_dummy = ifelse(monuments == 0, 0, 1))
```


```{r warning=FALSE, message=FALSE}
county_data <- read_csv("data/acharya_et_al_2016_county_data.csv")

county_data_cces <- read_csv("data/acharya_et_al_2016_cces_white_countydata.csv") %>% 
  dplyr::select(fips, dem, rep, affirm, resent)



names_by_county_1930 <- read_csv('data/full count census/southern_first_names_by_county_1930.csv')
names_by_county_1880 <- read_csv('data/full count census/southern_first_names_by_county_1880_final.csv')


county_data <- county_data %>% 
  mutate(fips_char = str_pad(fips, 5, pad = "0")) %>% 
  left_join(names_by_county_1930, by = c('fips_char' = 'fips'), suffix = c('', '_1930')) %>% 
  left_join(names_by_county_1880, by = c('fips_char' = 'fips'), suffix = c('', '_1880')) %>% 
  left_join(county_data_cces, by = "fips")


names(county_data)


county_data <- county_data %>% 
  right_join(counties, by = c("fips")) %>%
  mutate(share_southern_names_1930 =(first_name_stonewall + first_name_robert_e+ first_name_braxton +first_name_jubal+ first_name_robert_l)/n_obs,
         share_southern_names_1880 =(first_name_stonewall_1880 + first_name_robert_e_1880+ first_name_braxton_1880 +first_name_jubal_1880+ first_name_robert_l_1880)/n_obs_1880) 

county_data %>% 
  filter(is.na(share_southern_names_1880))

county_data <- county_data %>% 
  rename(wall1968 = wallace68.alt, thur1948 = thurmond48)


#county_data <- county_data %>% 
#  full_join(counties, by = c("fips")) %>% 
#  mutate(march = ifelse(is.na(march), 0, march))

full_controls <- c('+ pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860) + state.abb')

```


```{r}
county_data %>% 
  map_dbl(~sum(is.na(.)))
```


## Making maps
```{r}

sm_counties_map <- counties %>% 
  ggplot(aes(fill = as.factor(march))) +
    geom_sf(color = "gray50", size = 0.5) +
    geom_sf(data = st_transform(sherman_march_map, crs = "+proj=longlat +datum=WGS84 +no_defs"), fill = "black", size = 1)+
    theme_void() +
    coord_sf(crs = "+proj=longlat +datum=WGS84 +no_defs", ndiscr = F) + 
    labs(fill = "Sherman's March") + 
    theme(legend.position="bottom")

ggsave(here::here('figures/sm_counties_map.pdf'), sm_counties_map)

```


```{r}
counties %>%
  left_join(county_data, by = 'fips') %>% 
    #st_transform(crs = 7801) %>% 
  ggplot(aes(fill = pslave1860)) +
    geom_sf(color = "gray50", size = 0.5) +
    geom_sf(data = st_transform(sherman_march_map$geometry, crs = "+proj=longlat +datum=WGS84 +no_defs"), fill = "black", size = 1)+
    theme_void() +
    coord_sf(crs = "+proj=longlat +datum=WGS84 +no_defs", ndiscr = F) + 
    labs(fill = "Proportion of slaves in 1860") +
    scale_fill_gradient(low = "white", high = "red")

ggsave(here::here('figures/slave_share_counties_map.pdf'))


counties %>%
  left_join(county_data, by = 'fips') %>% 
    #st_transform(crs = 7801) %>% 
  ggplot(aes(fill = totpop1860)) +
    geom_sf(color = "gray50", size = 0.5) +
    geom_sf(data = st_transform(sherman_march_map$geometry, crs = "+proj=longlat +datum=WGS84 +no_defs"), fill = "black", size = 1)+
    theme_void() +
    coord_sf(crs = "+proj=longlat +datum=WGS84 +no_defs", ndiscr = F) + 
    labs(fill = "Total population in 1860") +
    scale_fill_gradient(low = "white", high = "red")

ggsave(here::here('figures/total_pop_counties_map.pdf'))



counties %>%
  left_join(county_data, by = 'fips') %>% 
    #st_transform(crs = 7801) %>% 
  ggplot(aes(fill = share_southern_names_1880)) +
    geom_sf(color = "gray50", size = 0.5) +
  #  geom_sf(data = st_transform(counties, crs = "+proj=longlat +datum=WGS84 +no_defs"), fill = "black", size = 2)+
    theme_void() +
    coord_sf(crs = "+proj=longlat +datum=WGS84 +no_defs", ndiscr = F) + 
    labs(fill = "Proportion of slaves in 1860") +
    scale_fill_gradient(low = "white", high = "red")


counties %>%
  left_join(county_data, by = 'fips') %>% 
  filter(n_obs < 12000) %>% 
    #st_transform(crs = 7801) %>% 
  ggplot(aes(fill = n_obs_1880)) +
    geom_sf(color = "gray50", size = 0.5) +
  #  geom_sf(data = st_transform(counties, crs = "+proj=longlat +datum=WGS84 +no_defs"), fill = "black", size = 2)+
    theme_void() +
    coord_sf(crs = "+proj=longlat +datum=WGS84 +no_defs", ndiscr = F) + 
    labs(fill = "Proportion of slaves in 1860") +
    scale_fill_gradient(low = "white", high = "red") #+   scale_fill_continuous()




counties %>%
  left_join(county_data, by = 'fips') %>% 
    #st_transform(crs = 7801) %>% 
  ggplot(aes(fill = sl_inst)) +
    geom_sf(color = "gray50", size = 0.5) +
  #  geom_sf(data = st_transform(counties, crs = "+proj=longlat +datum=WGS84 +no_defs"), fill = "black", size = 2)+
    theme_void() +
    coord_sf(crs = "+proj=longlat +datum=WGS84 +no_defs", ndiscr = F) + 
    labs(fill = "Proportion of slaves in 1860") +
    scale_fill_gradient(low = "white", high = "red") #+   scale_fill_continuous()



```

```{r}
county_data %>% 
  ggplot(aes(fill = pdem1900)) +
    geom_sf(color = "gray50", size = 0.5) +
    geom_sf(data = st_transform(sherman_march_map, crs = "+proj=longlat +datum=WGS84 +no_defs"), fill = "black", size = 2)+
    theme_void() +
    coord_sf(crs = "+proj=longlat +datum=WGS84 +no_defs", ndiscr = F) + 
    labs(fill = "Proportion of vote for Democrats  in 1900") +
    scale_fill_gradient(low = "white", high = "red") +
   theme(legend.position="bottom")


```

## Descriptive statistics
```{r}
vars_for_table_1 <- c('pslave1860')

county_data %>%
  pivot_longer(vars_for_table_1, names_to = 'variables') %>% 
  group_by(variables) %>% 
  summarise(mean_slave = mean(pslave1860), )

county_data$march_label <- ifelse(county_data$march, "On march's path", "Off march's path")



table1::label(county_data$pslave1860) <- "Share of slaves in 1860"
table1::label(county_data$pdem1848) <- "Dem. vote share in 1848"
table1::label(county_data$pdem1860) <- "Dem. vote share in 1860"
table1::label(county_data$pdem1872) <- "Dem. vote share in 1872"
table1::label(county_data$pdem1900) <- "Dem. vote share in 1900"



table1::label(county_data$land.ineq1860) <- "Land inequality in 1860"
table1::label(county_data$acimp1860) <- "Acres of improv. land in 1860"
table1::label(county_data$fvalpac1860) <- "Farm value per acre in 1860"
table1::label(county_data$totpop1860) <- "Total population in 1860"
table1::label(county_data$rail1860) <- "Railway access in 1860"
county_data$lynchrate_used  <- county_data$lynchrate *100
table1::label(county_data$lynchrate_used) <- "Lynch rate"



desc_table <- table1::table1(~totpop1860 + pslave1860+  land.ineq1860+acimp1860
                             + fvalpac1860 +rail1860 + lynchrate_used+  pdem1848 +pdem1860 +pdem1872 + pdem1900 
                             | march_label, data = county_data)

desc_table_df <- as_tibble(read_html(desc_table) %>% html_table(fill=TRUE, header = T), .name_repair = 'universal')



desc_table_df <- as_tibble(read_html(desc_table) %>% html_table(fill=TRUE), .name_repair = 'unique')
names(desc_table_df) <- 'Varaibles'


#as_data_frame(read_html(desc_table) %>% html_table(fill=TRUE))

that_cell <- c(rep(c(T, F, F), 6), rep(c(T, F, F, F), 5))
linesep <- c( rep(c("", "", "\\addlinespace"), 6), rep(c("", "", "", "\\addlinespace"), 5))

length(that_cell) == nrow(desc_table_df$Varaibles)

desc_table_df$Varaibles %>% 
  kbl('latex', digits = 3, caption = "Summary statistics I", escape = T, booktabs = T, label = 'desc_stat',
      linesep = linesep, position = 'h', align = 'lccc') %>% 
  kable_styling(font_size = 8) %>%
  column_spec(1, bold = that_cell) %>% 
  #add_header_above(c(" " = 2, "Control group" = 3, "Treatment-control" = 2)) %>% 
  save_kable(file = 'tables/desc_stats_i.tex')


```



```{r}

names(county_data)

table1::label(county_data$monuments_dummy) <- "Conf. monuments (dummy)"
table1::label(county_data$pct_conf_streets_surname) <- "Conf. streets share (%)-lenient"
table1::label(county_data$pct_conf_streets_both) <- "Conf. streets share (%)-strict"
county_data$pct_conf_names_1930  <- county_data$share_southern_names_1930 *100
county_data$pct_conf_names_1880  <- county_data$share_southern_names_1880 *100
table1::label(county_data$pct_conf_names_1930) <- "Conf. names share (%)-1930 census"
table1::label(county_data$pct_conf_names_1880) <- "Conf. names share (%)-1880 census"


desc_table <- table1::table1(~pct_conf_names_1880 + pct_conf_names_1930+  monuments_dummy+
                               pct_conf_streets_surname + pct_conf_streets_both
                             | march_label, data = county_data)

desc_table_df <- as_tibble(read_html(desc_table) %>% html_table(fill=TRUE), .name_repair = 'unique')
names(desc_table_df) <- 'Varaibles'


that_cell <- c(rep(c(T, F, F, F), 1), rep(c(T, F, F),4))
linesep <- c(rep(c("", "", "", "\\addlinespace"), 1), rep(c("", "", "\\addlinespace"), 4))

length(that_cell) == nrow(desc_table_df$Varaibles)

desc_table_df$Varaibles %>% 
  kbl('latex', digits = 3, caption = "Summary statistics I", escape = T, booktabs = T, label = 'desc_stat_names',
      linesep = linesep, position = 'h', align = 'lccc') %>% 
  kable_styling(font_size = 8) %>%
  column_spec(1, bold = that_cell) %>% 
  #add_header_above(c(" " = 2, "Control group" = 3, "Treatment-control" = 2)) %>% 
  save_kable(file = 'tables/desc_stats_names.tex')


```


## Estimation


Now let's try to add the results of Storm Thurmond in 1948 and George Wallace in 1968.
```{r}
fit_model <- function(dep_var, controls = "", iv = 0){
  if(iv == 0){
    
 lm_robust(as.formula(paste0(dep_var, " ~ march", controls)), data = county_data) %>% 
  tidy(conf.int = TRUE)
    
  } else{
    
 iv_robust(as.formula(paste0(dep_var, " ~ march", controls, '| sl_inst', controls)), data = county_data) %>% 
  tidy(conf.int = TRUE)
    
  }
}

get_coefs <- function(dep_var_vector, controls = "", year_vec = pdem, iv = 0){
 map(dep_var_vector, ~ fit_model(dep_var = ., controls = controls, iv = iv)) %>% 
  set_names(year_vec) %>% 
  map2(year_vec, ~ mutate(.x, year = .y)) %>% 
  bind_rows() %>% 
  filter(term == "march") %>% 
  mutate(
    party_type = str_sub(year, end = 4) %>% 
      fct_recode("Democrat" = "pdem", "Thurmond" = "thur", "Wallace" = "wall"), 
    year = as.numeric(str_sub(year, start = -4)),
    year = ifelse(party_type == "Thurmond", 1948.4, year),# Add slight offset to Thurmond that the conf. int. can be distinguished
    year = ifelse(party_type == "Democrat" & year == 1948, 1947.4, year)
    )
}


plot_coefs <- function(coef_data){
  coef_data %>% 
  ggplot(aes(x = year, y = estimate, ymin = conf.low, ymax = conf.high, col = party_type)) + 
  geom_pointrange() + 
  geom_hline(yintercept = 0, col = "black")+
    geom_vline(xintercept = 1864.75, col = "red", linetype = "dashed")+
  labs(caption = 'The error bars show 95% confidence intervals', y = 'Effect on vote shares of pres. candidates (%)',
       x = 'Year')+
    theme_minimal()+
  theme(axis.line = element_line(size = 1),
        axis.ticks.x = element_line(size = 1, colour = "gray"), 
        axis.ticks.y = element_line(size = 1, colour = "gray"),
                   axis.ticks.length = unit(5, "pt"),
        legend.position="bottom",
       # axis.ticks.length = unit(-0.3, "lines"),
      #  axis.ticks.margin = unit(0.5, "lines"),
        #axis.ticks.length=unit(.25, "cm"),
      #  panel.grid.major.x = element_blank(), 
      #  panel.grid.minor.x = element_blank(), 
        #axis.ticks.margin = unit(0.5, "lines"),
        text = element_text(size=16)#, axis.text.x = element_text(angle = x_labels_angle, hjust = x_labels_hjust)
        )+
  scale_color_manual(values = c("Democrat" = "black",
                                "Wallace"="blue",
                                "Thurmond"="green"), 
                     name = "Candidate") 
}

```



### OLS
```{r}
pdem <- paste0("pdem", seq(from = 1872, to = 1964, by = 4))
pdem <- c(paste0("pdem", seq(from = 1848, to = 1860, by = 4)), pdem)
pdem <- c(pdem, "wall1968", "thur1948")



coef_plot_no_controls<- pdem %>% 
  get_coefs() %>% 
  plot_coefs()

ggsave('figures/pdem_coef_plot_no_controls.pdf', coef_plot_no_controls)

```



```{r full controls}

full_controls <- c('+ pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860) + state.abb')


pdem_march_coefs_full_controls <- pdem %>% 
  get_coefs(controls = full_controls) %>% 
  plot_coefs() 

#ggsave('figures/pdem_coef_plot_full_controls.pdf', pdem_march_coefs_full_controls)

ggsave('figures/pdem_coef_plot_full_controls_pre.pdf', pdem_march_coefs_full_controls)




```


```{r}
county_data %>% 
  summarize(thur1948 = mean(thur1948, na.rm=T))
```


```{r}
pdem_diff <- paste0('I(', pdem,  ') - pdem1860')

coef_plot_diff  <- pdem_diff %>% 
  get_coefs(controls = "+ pslave1860") %>% 
  plot_coefs()

ggsave('figures/pdem_coef_plot_slave_diff.pdf', pdem_march_coefs_slave_control)


coef_plot_diff_no_controls  <- pdem_diff %>% 
  get_coefs(controls = "") %>% 
  plot_coefs()
```

```{r recent political outcomes}
wht_obama_vote_lm <- lm_robust(as.formula(paste0("wht.obama.vote", " ~ march", full_controls)), data = county_data)

county_data$dem_pct <- county_data$dem * 100
county_data$rep_pct <- county_data$rep * 100
county_data$affirm_pct <- county_data$affirm * 100

dem_lm <- lm_robust(as.formula(paste0("dem_pct", " ~ march", full_controls)), data = county_data)
rep_lm <- lm_robust(as.formula(paste0("rep_pct", " ~ march", full_controls)), data = county_data)
affirm_lm <- lm_robust(as.formula(paste0("affirm_pct", " ~ march", full_controls)), data = county_data)



gm <- list(
    list("raw" = "N", "clean" = "Number of observations", "fmt" = "%.0f"),
    list("raw" = "dv_mean", "clean" = "Dep. var. mean", "fmt" = "%.3f"),
    list("raw" = "r.squared", "clean" = "$R^2$", "fmt" = "%.3f")
)


glance_custom.lm_robust <- function(x, ...) {
    dv <- as.character(formula(x)[2])
    dv_mean <- mean(county_data %>% pull(dv), na.rm = TRUE)
    out <- data.frame("dv_mean" = dv_mean)
    return(out)
}



# check year in lynchings
note_text <- "All the control variables show their value as of 1860 (i.e. slave share in 1860 etc.). The standard errors based on HC2 variance estimator are in the parentheses. State fixed effects are included in all specifications. Dem. (Rep.) share is defined as the proportion of respondents in a given county who identify as a Democrat (Republican). Affirm. action sup. us defined as the share of respondents in a given county who support affirmative action policies. All three dependent variables are based on answers in CCES surveys and the shares are calculated only among white respondents.  "

modelsummary(list("Prop. Democrat" = dem_lm, "Prop. Republican" = rep_lm,
                  "Affirm. action" = affirm_lm), 
             coef_rename=c("march"="Sherman's march", "pslave1860"="Slave share",
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per ac.",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land"),   
             notes = note_text,
             title = "CCES outcomes - OLS results", label = "tab:other_outcomes_ols_all", 
             coef_omit = "^state", gof_map = gm,
             stars = TRUE)

modelsummary(list("Dem. share (%)" = dem_lm, "Rep. share (%)" = rep_lm,
                  "Affirm. action sup. (%)" = affirm_lm), 
             coef_rename=c("march"="Sherman's march", "pslave1860"="Slave share",
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per ac.",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land"),   
             notes = note_text,
             title = "CCES outcomes - OLS results", label = "tab:other_outcomes_ols_all", 
             coef_omit = "^state", gof_map = gm,
             stars = TRUE, output = "tables/cces_outcomes_ols_all.tex", escape=F)

```


```{r ols other outcomes table}
monuments_lm <- lm_robust(monuments_dummy ~ march + pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860)+ state.abb, data = county_data)


county_data$lynchrate_times_100 <- county_data$lynchrate * 100

lynchrate_lm <- lm_robust(lynchrate_times_100 ~ march + pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860)+ state.abb, data = county_data)

county_data$share_southern_names_1930_pct <- county_data$share_southern_names_1930 * 100
names_lm_1930 <- lm_robust(share_southern_names_1930_pct ~ march + pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860) + state.abb, data = county_data)

county_data$share_southern_names_1880_pct <- county_data$share_southern_names_1880 * 100
names_lm_1880 <- lm_robust(share_southern_names_1880_pct ~ march + pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860)+ state.abb, data = county_data)

names(county_data)

streets_lm <- lm_robust(pct_conf_streets_surname ~ march + pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860) + state.abb , data = county_data)

names(county_data)


summary(streets_lm)



gm <- list(
    list("raw" = "N", "clean" = "Number of observations", "fmt" = "%.0f"),
    list("raw" = "dv_mean", "clean" = "Dep. var. mean", "fmt" = "%.3f"),
    list("raw" = "r.squared", "clean" = "$R^2$", "fmt" = "%.3f")
)

glance(streets_lm)

glance_custom.lm_robust <- function(x, ...) {
    dv <- as.character(formula(x)[2])
    dv_mean <- mean(county_data %>% pull(dv), na.rm = TRUE)
    out <- data.frame("dv_mean" = dv_mean)
    return(out)
}



# check year in lynchings
note_text <- "All the control variables show their value as of 1860 (i.e. slave share in 1860 etc.). The standard errors based on HC2 variance estimator are in the parentheses. State fixed effects are included in all specifications. First names (1880)	is the share  (in %) of whites born after 1865 in a given county with first name that we classified as Confederate in 1880 census. First names (1930) is defined the same, only 1930 census is used. Street names is the share (in %) of streets and roads in a given that contain a surname of a Confederate figure in their name. Monuments is a an indicator variable that equals one if a Confederate monument was present in a county in 2019. Lynch rate is defined as the number of lynchings in a county from 1882 to 1929 per  10,000,000 residents. "

modelsummary(list("First names (1880)" = names_lm_1880, "First names (1930)" = names_lm_1930,
                  "Street names" = streets_lm, 'Monuments' = monuments_lm, 'Lynch rate' = lynchrate_lm), 
             coef_rename=c("march"="Sherman's march", "pslave1860"="Slave share",
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per ac.",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land"),   
             notes = note_text,
             title = "Other outcomes - OLS results", label = "tab:other_outcomes_ols_all", 
             coef_omit = "^state", gof_map = gm,
             stars = TRUE)

modelsummary(list("First names (1880)" = names_lm_1880, "First names (1930)" = names_lm_1930,
                  "Street names" = streets_lm, 'Monuments' = monuments_lm, 'Lynch rate' = lynchrate_lm), 
             coef_rename=c("march"="Sherman's march", "pslave1860"="Slave share",
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per ac.",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land"),   
             notes = note_text,
             title = "Other outcomes - OLS results \\label{tab:other_outcomes_iv_all_ss}", label = F,
             #label = "tab:other_outcomes_ols_all", 
             coef_omit = "^state", gof_map = gm,
             stars = TRUE, output = "tables/other_outcomes_ols_all.tex", escape=F)


```


## Difference-in-differences
```{r}


county_data$pdem_diff_1872 <- county_data$pdem1872 - county_data$pdem1860

did_no_controls <- lm_robust(pdem_diff_1872 ~ march, data = county_data %>% filter(state.abb != 'SC'))

did_full_controls <- lm_robust(pdem_diff_1872 ~ march + pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860) + state.abb, data = county_data %>% filter(state.abb != 'SC'))


county_data$pdem_diff_1900 <- county_data$pdem1900 - county_data$pdem1860

did_no_controls_1900 <- lm_robust(pdem_diff_1900 ~ march, data = county_data %>% filter(state.abb != 'SC'))

did_full_controls_1900 <- lm_robust(pdem_diff_1900 ~ march + pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860) + state.abb, data = county_data %>% filter(state.abb != 'SC'))


gm <- list(
    list("raw" = "N", "clean" = "Number of observations", "fmt" = "%.0f"),
    list("raw" = "dv_mean", "clean" = "Dep. var. mean", "fmt" = "%.3f"),
    list("raw" = "r.squared", "clean" = "$R^2$", "fmt" = "%.3f")
)


glance_custom.lm_robust <- function(x, ...) {
    dv <- as.character(formula(x)[2])
    dv_mean <- mean(county_data %>% pull(dv), na.rm = TRUE)
    out <- data.frame("dv_mean" = dv_mean)
    return(out)
}




modelsummary(list('(1)' = did_no_controls, '(2)' = did_full_controls), 
             coef_rename=c("march"="Sherman march", "pslave1860"="Slave share",
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per ac.",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land", "state.abbNC" = "North Carolina dummy"),   
             notes = "All the control variables are measured as of 1860", gof_map = gm,
             title = "Other outcomes - OLS results", label = "tab:other_outcomes_ols_all", 
             stars = TRUE)

gt_tab <- modelsummary(list('(1)' = did_no_controls, '(2)' = did_full_controls, 
                            '(3)' = did_no_controls_1900, '(4)' = did_full_controls_1900), 
             coef_rename=c("march"="Sherman's march", "pslave1860"="Slave share", 
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per acre",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land", "state.abbNC" = "North Carolina dummy"),
             gof_map = gm, 
           #  output = "tables/diff_in_diff.tex", 
              output = "gt", 
             notes = "All the control variables show their value as of 1860 (i.e. slave share in 1860 etc.). The standard errors based on HC variance estimator are in the parentheses. South Carolina counties were excluded due to the absence of popular vote in 1860 and before. ",
             label = "tab:did", stars = TRUE, 
             title = "Democratic vote share difference (in percantage points)")
gt_tab %>% 
  tab_spanner(label = '1860-1872', columns = 2:3) %>%
  tab_spanner(label = '1860-1900', columns = 4:5) %>% 
    gtsave('diff_in_diff_more_years.tex', path = here('tables'), escape=F)



```


## Instrumental variable
```{r}
straight_line_inst <- editMap()


saveRDS(straight_line_inst, file = here::here("maps/straight_line_inst.RData"))


```


```{r}
straight_line_inst <- readRDS(here::here("maps/straight_line_inst.RData"))


straight_line_buffer_20km <- straight_line_inst %>% 
  st_transform(crs = 7801) %>% 
  st_buffer(dist = 20000, nQuadSegs = 1) 

#mapview(straight_line_buffer_20km)


inst_counties <- counties %>% 
  st_transform(crs = 7801) %>% 
  #st_as_s2() %>% 
  st_intersection(straight_line_buffer_20km) %>% 
  st_set_geometry(NULL) %>% 
  distinct(fips) %>% #count(fips, sort = T)
  dplyr::select(fips) %>% 
  mutate(sl_inst = 1)



county_data <- county_data %>% 
  left_join(inst_counties, by = "fips") %>% 
  mutate(sl_inst = ifelse(is.na(sl_inst), 0, sl_inst))

```

```{r}

exo_vars <- '+ pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860) + state.abb'

iv_out <- iv_robust(pdem1900 ~ march + pslave1860 | sl_inst + pslave1860, data = county_data)


iv_dem_share <- pdem %>% 
  get_coefs(controls = exo_vars, iv = 1) %>% 
  plot_coefs()


#ggsave('figures/pdem_coef_plot_iv_controls.pdf', iv_dem_share)
ggsave('figures/pdem_coef_plot_iv_controls_pre.pdf', iv_dem_share)

```





```{r second stage tables}

lynchrate_iv <- iv_robust(as.formula(str_c("lynchrate_times_100  ~", 'march', exo_vars, "|sl_inst", exo_vars)),
                          data = county_data) 


monuments_iv <- iv_robust(as.formula(str_c("monuments_dummy ~", 'march', exo_vars, "|sl_inst", exo_vars)),
                          data = county_data) 

names_iv_1930 <- iv_robust(as.formula(str_c("share_southern_names_1930_pct ~", 'march', exo_vars, "|sl_inst", exo_vars)),
                          data = county_data) 


names_iv_1880 <- iv_robust(as.formula(str_c("share_southern_names_1880_pct ~", 'march', exo_vars, "|sl_inst", exo_vars)),
                          data = county_data) 


streets_iv <- iv_robust(as.formula(str_c("pct_conf_streets_surname ~", 'march', exo_vars, "|sl_inst", exo_vars)),
                          data = county_data) 


summary(streets_iv)

#streets_iv$


glance_custom.iv_robust <- function(x, ...) {
    dv <- as.character(formula(x)[2])
    dv_mean <- mean(county_data %>% pull(dv), na.rm = TRUE)
    out <- data.frame("dv_mean" = dv_mean)
    return(out)
}


gm <- list(
    list("raw" = "N", "clean" = "Number of observations", "fmt" = "%.0f"),
    list("raw" = "dv_mean", "clean" = "Dep. var. mean", "fmt" = "%.3f"),
    list("raw" = "r.squared", "clean" = "$R^2$", "fmt" = "%.3f")
)



glance(streets_lm)

glance_custom(streets_lm)

# check year in lynchings
note_text <- "All the control variables show their value as of 1860 (i.e. slave share in 1860 etc.). The standard errors based on HC variance estimator are in the parentheses. State fixed effects are included in all specifications. First names (1880)	is the share (in %) of whites born after 1865 in a given county with first name that we classified as Confederate in 1880 census. First names (1930) is defined the same, only 1930 census is used. Street names is the share (in %) of streets and roads in a given that contain a surname of a Confederate figure in their name. Monuments is a an indicator variable that equals one if a Confederate monument was present in a county in 2019. Lynch rate is defined as the number of lynchings in a county from 1882 to 1929 per  10,000,000 residents. "

modelsummary(list("First names (1880)" = names_iv_1880, "First names (1930)" = names_iv_1930,
                  "Street names" = streets_iv, 'Monuments' = monuments_iv, 'Lynch rate' = lynchrate_iv), 
             coef_rename=c("march"="Sherman march", "pslave1860"="Slave share",
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per ac.",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land"),   
             notes = note_text,
             title = "Other outcomes - IV - second stage", label = "tab:other_outcomes_iv_all_ss", 
             coef_omit = "^state", gof_map = gm,
             stars = TRUE)

modelsummary(list("First names (1880)" = names_iv_1880, "First names (1930)" = names_iv_1930,
                  "Street names" = streets_iv, 'Monuments' = monuments_iv, 'Lynch rate' = lynchrate_iv), 
             coef_rename=c("march"="Sherman march", "pslave1860"="Slave share",
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per ac.",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land"),   
             notes = note_text,
             title = "Other outcomes - IV - second stage \\label{tab:other_outcomes_iv_all_ss}", label = F,
             #label = "tab:other_outcomes_iv_all_ss", 
             coef_omit = "^state", gof_map = gm,
             stars = TRUE, output = "tables/other_outcomes_iv_all_ss.tex", escape=F)

#https://www.r-bloggers.com/2014/05/stacking-regressions-latex-tables-with-r-and-stargazer/


```


```{r iv recent political outcomes}
wht_obama_vote_iv <- iv_robust(as.formula(str_c("wht.obama.vote ~", 'march', exo_vars, "|sl_inst", exo_vars)), data = county_data)

dem_iv <- iv_robust(as.formula(paste0("dem_pct ~", 'march', exo_vars, "|sl_inst", exo_vars)), data = county_data)
rep_iv <- iv_robust(as.formula(paste0("rep_pct ~", 'march', exo_vars, "|sl_inst", exo_vars)), data = county_data)

affirm_iv <- iv_robust(as.formula(paste0("affirm_pct ~", 'march', exo_vars, "|sl_inst", exo_vars)), data = county_data)



gm <- list(
    list("raw" = "N", "clean" = "Number of observations", "fmt" = "%.0f"),
    list("raw" = "dv_mean", "clean" = "Dep. var. mean", "fmt" = "%.3f"),
    list("raw" = "r.squared", "clean" = "$R^2$", "fmt" = "%.3f")
)


glance_custom.iv_robust <- function(x, ...) {
    dv <- as.character(formula(x)[2])
    dv_mean <- mean(county_data %>% pull(dv), na.rm = TRUE)
    out <- data.frame("dv_mean" = dv_mean)
    return(out)
}



# check year in lynchings
note_text <- "All the control variables show their value as of 1860 (i.e. slave share in 1860 etc.). The standard errors based on HC2 variance estimator are in the parentheses. State fixed effects are included in all specifications. Dem. (Rep.) share is defined as the proportion of respondents in a given county who identify as a Democrat (Republican). Affirm. action sup. us defined as the share of respondents in a given county who support affirmative action policies. All three dependent variables are based on answers in CCES surveys and the shares are calculated only among white respondents. "

modelsummary(list("Dem. share (\%)" = dem_iv, "Rep. share (\%)" = rep_iv,
                  "Affirm. action sup. (%)" = affirm_iv), 
             coef_rename=c("march"="Sherman's march", "pslave1860"="Slave share",
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per ac.",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land"),   
             notes = note_text,
             title = "CCES outcomes - OLS results", label = "tab:other_outcomes_ols_all", 
             coef_omit = "^state", gof_map = gm,
             stars = TRUE)


modelsummary(list("Dem. share (%)" = dem_iv, "Rep. share (%)" = rep_iv,
                  "Affirm. action sup. (%)" = affirm_iv), 
             coef_rename=c("march"="Sherman's march", "pslave1860"="Slave share",
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per ac.",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land"),   
             notes = note_text,
             title = "CCES outcomes - IV results", label = "tab:other_outcomes_iv_all", 
             coef_omit = "^state", gof_map = gm,
             stars = TRUE, output = "tables/cces_outcomes_iv_all.tex", escape=F)




```



```{r first stage}

library(AER)

iv_reg_sum <- ivreg(monuments_dummy ~ march + pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860)+ state.abb | sl_inst + pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860)+ state.abb, data = county_data) %>% 
  summary(diagnostics = T)

iv_reg_sum$diagnostics[1,3]
summary(iv_reg_sum)


note_text <- "All the control variables show their value as of 1860 (i.e. slave share in 1860 etc.). The standard errors based on HC2 variance estimator are in the parentheses. State fixed effects are included. "



first_stage_res <- lm_robust(march ~ sl_inst + pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860)+ state.abb, data = county_data)

summary(first_stage_res)

first_stage_res_lm <- lm(march ~ sl_inst + pslave1860 + land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860)+ state.abb, data = county_data)

summary(first_stage_res_lm)

summary(first_stage_res)

gm <- list(
  list("raw" = "r.squared", "clean" = "$R^2$", "fmt" = "%.3f"),
  list("raw" = "statistic", "clean" = "F-statistic", "fmt" = "%.2f"),
    list("raw" = "N", "clean" = "N", "fmt" = "%.0f")
)

glance(first_stage_res)


modelsummary(list("Sherman's march" = first_stage_res), 
             coef_rename=c("sl_inst"="Straight-line instrument", "pslave1860"="Slave share",
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per ac.",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land"),   
             notes = note_text,
             title = "IV - first stage", label = "tab:iv_fs", 
             coef_omit = "^state", gof_map = gm,
             stars = TRUE)


modelsummary(list("Sherman's march" = first_stage_res), 
             coef_rename=c("sl_inst"="Straight-line instrument", "pslave1860"="Slave share",
                           "land.ineq1860" = "Land inequality", "log(fvalpac1860)" = "Log of farm value per ac.",
                           "rail1860" = "Railway access", "log(totpop1860)" = "Log of total population",
                           "log(acimp1860)" = "Log of acres of improved land"),   
             notes = note_text,
             title = "IV - first stage", label = "tab:iv_fs", 
             coef_omit = "^state", gof_map = gm,
             stars = TRUE, output = "tables/iv_fs.tex")



first_stage_res


```


```{r weak instrument test}
#x <- data.frame(a = rnorm(3), b = letters[1:3])
#stata("sum a", data.in = x)
county_data_no_gem <- as.data.frame(county_data)
county_data_no_gem$geometry <- NULL

county_data_no_gem <- county_data_no_gem %>% 
  rename(land_ineq1860 = land.ineq1860, state_abb = state.abb) %>% 
  mutate(log_totpop1860 = log(totpop1860),
         log_acimp1860 = log(acimp1860),
         log_fvalpac1860 = log(fvalpac1860),
         nc_d = (state_abb == "NC")*1,
         sc_d = (state_abb == "SC")*1,
         state_abb = as.factor(state_abb))

stata("reg pdem1900 march pslave1860", data.in = county_data_no_gem)

stata("ssc install weakivtest", data.in = county_data_no_gem)
stata("ssc install avar", data.in = county_data_no_gem)


stata("ivregress 2sls pct_conf_streets_surname pslave1860 land_ineq1860 log_totpop1860 log_acimp1860 rail1860 nc sc log_fvalpac1860 (march = sl_inst)
      weakivtest ", data.in = county_data_no_gem)

county_data_no_gem %>% 
  count(state_abb)

```



```{r}
county_data_no_gem <- county_data_no_gem %>% 
  rename(Y = pdem1900, D = march, Z = sl_inst)
```


```{r}
n = 3000; p = 3; rho=0.3
u <- rnorm(n)
v <- rho*u + sqrt(1-rho^2)*rnorm(n)
X <- matrix(rnorm(n * p), n, p)
colnames(X) <- paste("Xvar", 1:p, sep="")
Z <- rbinom(n, size = 1, prob = 0.5)
D<-as.numeric(0.2 * Z + v > 0)

# Local violation of the exclusion restriction:
gamma <- as.numeric(ifelse(X[, 2] < -1, 1.25, 0))
Y <- as.vector(D + gamma * Z + u)
data <- as.data.frame(cbind(Y,D,Z,X))

# Perform test:
covars = paste0(colnames(data)[4:ncol(data)])
test <- LATEtest(data = data, covars = covars, subsets = 4, alpha = 0.05)
test

```
### Testing coefficient stability
```{r oster test}
# load data, e.g. the in-build mtcars dataset
data("mtcars")
data_oster <- mtcars
# preview of data
head(data_oster)
# load robomit
require(robomit)
# estimate bootstrapped beta*s
betas <-  o_beta_boot_inf(y = "mpg", # dependent variable
x = "wt", # independent treatment variable
con = "hp + qsec", # related control variables
delta = 1, # delta
R2max = 0.9, # maximum R-square
sim = 100, # number of simulations
obs = 30, # draws per simulatio
rep = FALSE, # bootstrapping with or without replacement
type = "lm", # model type
useed = 123, # seed
CI = 95,
data = data_oster)

betas <-  o_beta_rsq(y = "mpg", # dependent variable
x = "wt", # independent treatment variable
con = "hp + qsec", # related control variables
delta = 1, # delta
type = "lm", # model type
data = data_oster)


deltas_mt <- o_delta_boot_inf(y = "mpg", x = "wt", con = "hp + qsec", beta = 0, R2max = 1, sim = 100, obs = 30, rep = FALSE,
                 CI = 95, type = "lm", useed = 123, data = data_oster)


deltas <- o_delta_boot_inf(y = "share_southern_names_1930_pct", 
                           x = "march",
                           m = "pslave1860",
                           con = "land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860)+ state.abb", 
                           beta = 0, 
                           R2max = 1, 
                           sim = 800, obs = 300, rep = TRUE,
                 CI = 95, type = "lm", useed = 123, data = county_data)


deltas

betas_names_1930 <- o_delta_boot(y = "share_southern_names_1930_pct", 
                          x = "march",
                          con = "land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860)+ state.abb",
                          m = "none",
                          R2max = 1, 
                          type = "lm",
                          sim = 800, obs = 305, rep = TRUE,
                          data = county_data)




oster_2019_est <- function(dep_var, n_obs = 350, n_sims = 1000){
  

betas_names <- o_beta_boot_inf(y = dep_var, 
                          x = "march",
                          con = "land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860)+ state.abb",
                          m = "none",
                          delta = 1,
                          R2max = 1, 
                          type = "lm",
                          sim = n_sims, obs = n_obs, rep = TRUE,
                          CI = 95,
                          data = county_data)


mean_beta <- betas_names %>% 
  filter(Name == "beta* (mean)") %>% 
  pull(Value) %>% 
  as.numeric()

conf_low <- betas_names %>% 
  filter(Name == "CI_95_low") %>% 
  pull(Value) %>% 
  as.numeric()

conf_high <- betas_names %>% 
  filter(Name == "CI_95_high") %>% 
  pull(Value) %>% 
  as.numeric()

output_df <- data.frame("Mean_effect" = mean_beta, "conf_low" = conf_low, "conf_high" = conf_high)

return(output_df)
}


oster_2019_est_deltas <- function(dep_var, n_obs = 350, n_sims = 1000){

delta_names <- o_delta_boot_inf(y = dep_var, 
                          x = "march",
                          con = "land.ineq1860 + log(acimp1860) + log(fvalpac1860) + rail1860 + log(totpop1860)+ state.abb",
                          m = "none",
                          R2max = 1, 
                          type = "lm",
                          sim = n_sims, obs = n_obs, rep = TRUE,
                          CI = 95,
                          data = county_data)


mean_delta <- delta_names %>% 
  filter(Name == "delta* (mean)") %>% 
  pull(Value) %>% 
  as.numeric()

conf_low <- delta_names %>% 
  filter(Name == "CI_95_low") %>% 
  pull(Value) %>% 
  as.numeric()

conf_high <- delta_names %>% 
  filter(Name == "CI_95_high") %>% 
  pull(Value) %>% 
  as.numeric()

output_df <- data.frame("Mean_effect" = mean_delta, "conf_low" = conf_low, "conf_high" = conf_high)

return(output_df)
}





dep_var_vec <- c("pdem1872" ,"pdem1900", "thur1948",
                 "share_southern_names_1880_pct",
                 "share_southern_names_1930_pct",
                 "pct_conf_streets_surname", 
                 "monuments_dummy",
                 "lynchrate_times_100")
n_missing <- dep_var_vec %>% 
  map_int(~sum(is.na(county_data[, .x])))
n_nonmissing_obs <- 305 - n_missing



betas_df <- map2(dep_var_vec, n_nonmissing_obs, ~ oster_2019_est(dep_var = .x, n_obs = .y))

betas_df <- betas_df %>% 
  bind_rows()




rownames(betas_df) <- c("Democrats' share in 1872",
                        "Democrats' share in 1900",
                        "Thurmond's share in 1948", 
                        "Conf. first names share-1880 census",
                        "Conf. first names share-1930 census",
                        "Conf. streets share",
                        "Conf. monument dummy",
                        "Lynch rate")

#colnames(betas_df) <- c("Bias-adj. treat. effect", "95\\% CI (lower b.)", "95\\% CI (upper b.)")

colnames(betas_df) <- c("Est. ", "95\\% CI (l.)", "95\\% CI (u.)")


deltas_df <- map2(dep_var_vec, n_nonmissing_obs, ~ oster_2019_est_deltas(dep_var = .x, n_obs = .y))

deltas_df <- deltas_df %>% 
  bind_rows()


colnames(deltas_df) <- c("Est.", "95\\% CI (l.) ", "95\\% CI (u.) ")

merge_df <- betas_df %>% 
  bind_cols(deltas_df)


 
note_text <- "First names (1880)	is the share (in %) of whites born after 1865 in a given county with first name that we classified as Confederate in 1880 census. First names (1930) is defined the same, only 1930 census is used. Street names is the share (in %) of streets and roads in a given that contain a surname of a Confederate figure in their name. Monuments is a an indicator variable that equals one if a Confederate monument was present in a county in 2019. Lynch rate is defined as the number of lynchings in a county from 1882 to 1929 per  10,000,000 residents."


merge_df %>% 
  kbl('latex', digits = 3, caption = "Sensitivity to unobservables using Oster (2019) methods", escape = F, 
      booktabs = T, label = 'oster_2019',
      position = 'h'#, align = 'cccccc'
      ) %>% 
#  kable_styling(font_size = 8) %>%
 # column_spec(1, bold = that_cell) %>% 
  add_header_above(c(" "=1, "Bias-adj. treament effect" = 3, "Strength of sel. on unob. ($\\delta$)" = 3), escape = F) %>% 
  add_footnote(input = note_text) %>% 
  save_kable(file = 'tables/oster_2019.tex')




betas_df

names(county_data)

county_data$share_southern_names_1930
```


Placebo IV
```{r}
urb_pop <- read_csv("data/nhgis0001_csv/nhgis0001_ds14_1860_county.csv")

urb_pop <- urb_pop %>% 
  mutate(fips = as.numeric(str_c(str_sub(STATEA, start = 1, end = -2), 
                                 str_sub(COUNTYA, start = 1, end = -2)))) %>%filter(STATE == 'Georgia')# %>%   filter(fips == 13003)



urb_pop %>% 
  count(fips, sort = T)


county_data <- county_data %>% 
  left_join(urb_pop, by = "fips")

county_data <- county_data %>% 
  rename(urb_population = AHF001) %>% 
  mutate(urban_centre = ifelse(urb_population > 0, 1, 0))


county_data %>% 
  inner_join(urb_pop, by = "fips")



counties

counties$centroids <- counties %>% 
  st_centroid() %>% 
  # this is the crs from d, which has no EPSG code:
  #st_transform(., '+proj=longlat +ellps=GRS80 +no_defs') %>%
  # since you want the centroids in a second geometry col:
  st_geometry()


sample_counties <- sample(1:nrow(counties), 3)

straight_line_point <- matrix(NA, nrow = 3, ncol = 2)
straight_line_point[1,1] <- counties$centroids[sample_counties[[1]]][[1]][[1]]
straight_line_point[1,2] <- counties$centroids[sample_counties[[1]]][[1]][[2]]
straight_line_point[2,1] <- counties$centroids[sample_counties[[2]]][[1]][[1]]
straight_line_point[2,2] <- counties$centroids[sample_counties[[2]]][[1]][[2]]
straight_line_point[3,1] <- counties$centroids[sample_counties[[3]]][[1]][[1]]
straight_line_point[3,2] <- counties$centroids[sample_counties[[3]]][[1]][[2]]


straight_line_string <- st_linestring(x = straight_line_point)


straight_line_inst$geometry[[1]] <- straight_line_string

plot(straight_line_inst)

temp <-counties$centroids[sample_counties[[1]]]
temp[[1]][[1]]


straight_line_string <- st_sfc(straight_line_string, crs = 4326, precision = 0)


straight_line_buffer_20km <- straight_line_string %>% 
  st_transform(crs = 7801) %>% 
  st_buffer(dist = 20000, nQuadSegs = 1) 

plot(straight_line_buffer_20km)
```





## Double ML


```{r}
library(mlr3)
library(mlr3learners)
# surpress messages from mlr3 package during fitting
lgr::get_logger("mlr3")$set_threshold("warn")

learner = lrn("regr.ranger", num.trees=500, mtry=4, max.depth=5, min.node.size=2)
ml_g = learner$clone()
ml_m = learner$clone()
ml_r = learner$clone()

#learner = lrn("regr.cv_glmnet", s="lambda.min")
#ml_g_sim = learner$clone()
#ml_m_sim = learner$clone()

```


```{r}
set.seed(3141)
obj_dml_plr = DoubleMLPLR$new(dml_data, ml_g=ml_g, ml_m=ml_m)
obj_dml_plr$fit()
print(obj_dml_plr)

obj_dml_plr_sim = DoubleMLPLR$new(dml_data_sim, ml_g=ml_g_sim, ml_m=ml_m_sim)
obj_dml_plr_sim$fit()
print(obj_dml_plr_sim)


obj_dml_plr
```


```{r}
confints = rbind(obj_dml_plr$confint(), obj_dml_plr$confint(),
                 obj_dml_plr$confint(), obj_dml_plr$confint())
estimates = c(obj_dml_plr$coef, obj_dml_plr$coef,
              obj_dml_plr$coef, obj_dml_plr$coef)

result_plr = data.table("model" = "PLR",
                        "ML" = c("glmnet", "ranger", "rpart", "xgboost"),
                        "Estimate" = estimates,
                        "lower" = confints[,1],
                        "upper" = confints[,2])
result_plr

g_ci = ggplot(result_plr, aes(x = ML, y = Estimate, color = ML)) +
        geom_point() +
        geom_errorbar(aes(ymin = lower, ymax = upper, color = ML))  +
        geom_hline(yintercept = 0, color = "grey") +
        theme_minimal() + ylab("Coefficients and 0.95- confidence interval") +
        xlab("") +
        theme(axis.text.x = element_text(angle = 90), legend.position = "none",
              text = element_text(size = 20))

g_ci


```


```{r plm coefplot}

x_controls <- c("pslave1860", "land.ineq1860", "acimp1860_log", "fvalpac1860_log", "rail1860", "totpop1860_log")
pdem <- paste0("pdem", seq(from = 1872, to = 1964, by = 4))
pdem <- c(paste0("pdem", seq(from = 1848, to = 1860, by = 4)), pdem)
pdem <- c(pdem, "wall1968", "thur1948")

pres_years <- c(seq(from = 1848, to = 1860, by = 4), seq(from = 1872, to = 1964, by = 4), 1968, 1948)
party_type <- c(rep("Democrat", length(pres_years)-2), "Wallace", "Thurmond")


fit_plm <- function(y_col = 'pdem1900', data = county_data, x_control_vec = x_controls){
  county_data_no_geom <- data %>% 
  mutate_at(vars(c('acimp1860', 'fvalpac1860', 'totpop1860')), list('log' = log)) %>% 
  filter(!is.na(!!rlang::sym(y_col)))

county_data_no_geom$geometry <- NULL


dml_data <- DoubleMLData$new(as.data.table(county_data_no_geom),
                             y_col = y_col,
                             d_cols = "march",
                             x_cols = x_control_vec)
set.seed(3141)
obj_dml_plr = DoubleMLPLR$new(dml_data, ml_g=ml_g, ml_m=ml_m)
obj_dml_plr$fit()
return(obj_dml_plr)
}

#new_plm_obj <- fit_plm()

#new_plm_obj$coef


new_plm_obj <- map(pdem, ~ fit_plm(.x, data = county_data))

plm_coefs <- map_dbl(new_plm_obj, ~ .$coef)

plm_conf_low <- map_dbl(new_plm_obj, ~ .$confint()[,1])
plm_conf_high <- map_dbl(new_plm_obj, ~ .$confint()[,2])

plm_data <- data.frame(plm_coefs = plm_coefs, plm_conf_low = plm_conf_low, plm_conf_high = plm_conf_high, 
                       year = pres_years, cand_party_type = party_type)


plm_coef_plot <- plm_data %>%  
  ggplot(aes(x = year, y = plm_coefs, ymin = plm_conf_low, ymax = plm_conf_high, col = cand_party_type)) + 
  geom_pointrange() + 
   geom_hline(yintercept = 0, col = "black")+
    geom_vline(xintercept = 1864.75, col = "red", linetype = "dashed")+
  labs(caption = 'The error bars show 95% confidence intervals', y = 'Effect on vote shares of pres. candidates (%)',
       x = 'Year')+
    theme_minimal()+
  theme(axis.line = element_line(size = 1),
        axis.ticks.x = element_line(size = 1, colour = "gray"), 
        axis.ticks.y = element_line(size = 1, colour = "gray"),
                   axis.ticks.length = unit(5, "pt"),
        legend.position="bottom",
       # axis.ticks.length = unit(-0.3, "lines"),
      #  axis.ticks.margin = unit(0.5, "lines"),
        #axis.ticks.length=unit(.25, "cm"),
      #  panel.grid.major.x = element_blank(), 
      #  panel.grid.minor.x = element_blank(), 
        #axis.ticks.margin = unit(0.5, "lines"),
        text = element_text(size=16)#, axis.text.x = element_text(angle = x_labels_angle, hjust = x_labels_hjust)
        )+
  scale_color_manual(values = c("Democrat" = "black",
                                "Wallace"="blue",
                                "Thurmond"="green"), 
                     name = "Candidate")


ggsave('figures/pdem_coef_plot_plm.pdf', plm_coef_plot)
  
new_var <- 'pdem1872'

county_data %>% 
  filter(!is.na({{new_var}}))


county_data %>% 
  filter(!is.na(all_of(new_var)))

!!rlang::sym()

county_data %>% 
  filter(!is.na(!!rlang::sym(new_var)))


county_data %>% 
  filter(!is.na(pdem1872))

```



```{r plm iv coefplot}
fit_plm_iv <- function(y_col = 'pdem1900', data = county_data, x_control_vec = x_controls, z_var = "sl_inst"){
  county_data_no_geom <- data %>% 
  mutate_at(vars(c('acimp1860', 'fvalpac1860', 'totpop1860')), list('log' = log)) %>% 
  filter(!is.na(!!rlang::sym(y_col)))

county_data_no_geom$geometry <- NULL


dml_data <- DoubleMLData$new(as.data.table(county_data_no_geom),
                             y_col = y_col,
                             d_cols = "march",
                             x_cols = x_control_vec,
                             z_cols = z_var)
set.seed(3141)
obj_dml_plr = DoubleMLPLIV$new(dml_data, ml_g=ml_g, ml_m=ml_m, ml_r=ml_r)
obj_dml_plr$fit()
return(obj_dml_plr)
}

#new_plm_obj <- fit_plm_iv()

#new_plm_obj$coef

new_plm_obj <- map(pdem, ~ fit_plm_iv(.x, data = county_data))

plm_coefs <- map_dbl(new_plm_obj, ~ .$coef)

plm_conf_low <- map_dbl(new_plm_obj, ~ .$confint()[,1])
plm_conf_high <- map_dbl(new_plm_obj, ~ .$confint()[,2])

pres_years <- c(seq(from = 1848, to = 1860, by = 4), seq(from = 1872, to = 1964, by = 4), 1968, 1948.5)


plm_data <- data.frame(plm_coefs = plm_coefs, plm_conf_low = plm_conf_low, plm_conf_high = plm_conf_high, 
                       year = pres_years, cand_party_type = party_type)


plm_coef_plot <- plm_data %>%  
  ggplot(aes(x = year, y = plm_coefs, ymin = plm_conf_low, ymax = plm_conf_high, col = cand_party_type)) + 
  geom_pointrange() + 
   geom_hline(yintercept = 0, col = "black")+
    geom_vline(xintercept = 1864.75, col = "red", linetype = "dashed")+
  labs(caption = 'The error bars show 95% confidence intervals', y = 'Effect on vote shares of pres. candidates (%)',
       x = 'Year')+
    theme_minimal()+
  theme(axis.line = element_line(size = 1),
        axis.ticks.x = element_line(size = 1, colour = "gray"), 
        axis.ticks.y = element_line(size = 1, colour = "gray"),
                   axis.ticks.length = unit(5, "pt"),
        legend.position="bottom",
       # axis.ticks.length = unit(-0.3, "lines"),
      #  axis.ticks.margin = unit(0.5, "lines"),
        #axis.ticks.length=unit(.25, "cm"),
      #  panel.grid.major.x = element_blank(), 
      #  panel.grid.minor.x = element_blank(), 
        #axis.ticks.margin = unit(0.5, "lines"),
        text = element_text(size=16)#, axis.text.x = element_text(angle = x_labels_angle, hjust = x_labels_hjust)
        )+
  scale_color_manual(values = c("Democrat" = "black",
                                "Wallace"="blue",
                                "Thurmond"="green"), 
                     name = "Candidate")


ggsave('figures/pdem_coef_plot_plm_iv.pdf', plm_coef_plot)



```

